network:
  location_file: "disaster_logistics_model/data/pacific_cities.csv"
  shift_longitudes: true

simulation:
  num_scenarios: 5
  severity_distribution:
    mean: 2.0
    std_dev: 0.5
  base_demand_food_per_capita: 5
  base_demand_water_per_capita: 15
  supply_fraction:
    value: 200.0  # Each node starts with 2x expected demand
    surplus_factor: 0.001  # Extra per-capita multiplier for inventory surplus
  capacity_per_capita:
    value: 5000
    surplus_factor: 0.001  # Extra capacity per capita based on population
  safety_days: 2  # Number of days of supply each node should maintain as safety stock

  scenario_profiles:
    coastal:
      impact_radius_mean_km: 500
      impact_radius_std_km: 100
      infrastructure_loss_min: 0.3
      infrastructure_loss_max: 0.4
    island_chain:
      impact_radius_mean_km: 800
      impact_radius_std_km: 200
      infrastructure_loss_min: 0.3
      infrastructure_loss_max: 0.4
    urban_cluster:
      impact_radius_mean_km: 300
      impact_radius_std_km: 50
      infrastructure_loss_min: 0.3
      infrastructure_loss_max: 0.4

optimization:
  P_max: 10  # Increase from 5
  required_safety_stock:
    food: 1000
    water: 1000
  M: 9900  # Adjusted Big-M value
  redundancy:
    food: 1
    water: 1
  commodities: ["food", "water"]
  max_num_vehicles: 1000  # Lowered from 10000


  region_proportions:
    1: 0.6
    2: 0.1
    3: 0.1

  objective_weights:
    deficit: 0.3
    shortfall: 0.3
    balance: 0.4  # Rename from prepositioning to match instructor logic

commodities:
  size:
    food: 1.0
    water: 1.0

vehicles:
  capacity:
    1: 1000.0
    2: 1000.0
    3: 1000.0
    4: 1000.0
    5: 1000.0

aps:
  min_per_commodity:
    food: 1
    water: 1

visualization:
  zoom_start: 3
  node_radius: 5
  node_color: 'blue'
  node_opacity: 0.7
  flow_color: 'green'
  flow_width: 2
  flow_opacity: 0.5
  epicenter_color: 'red'
  impact_rings_km: [500, 1000, 1500]

output:
  batch_summary_file: "disaster_logistics_model/output/batch_summary.csv"
  scenario_maps_folder: "disaster_logistics_model/output/scenario_maps"
