seed: 42
num_scenarios: 15

default_disaster:
  severity_range: [1.0, 5.0]
  affected_radius:
    base: 1
    multiplier: 1

commodities:
  - food
  - water

arc_capacity:
  base: 1000
  multiplier: 100